###
POST http://localhost:3000/api/items/createItem
Content-Type: application/json

{
    "name": "Ice Cream",
    "price": 2.50,
    "itemID": 1
}

###
GET http://localhost:3000/api/items/getItems

###
GET http://localhost:3000/api/customers/getCustomers

###
POST http://localhost:3000/api/orders/createOrder
Content-Type: application/json

{
    "orderNo": 12345,
    "customerID": "12345",
    "customerName" : "test api rest",
    "paymentMethod" : "CASH",
    "totalAmount" : 499 

}

###
GET http://localhost:3000/api/orders/getOrders

###
GET http://localhost:3000/api/orders/getOrder/5fd12718ae25e52710cf2899

###
DELETE http://localhost:3000/api/orders/deleteOrder/5fd1333ca567c72b70fb7931
